# Generated by Django 5.0.7 on 2024-08-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=40, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=40, verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name="Nom d'utilisateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_service', models.CharField(max_length=100, verbose_name='Libelle service')),
                ('description_service', models.TextField(null=True, verbose_name='Description du service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metier',
            name='description_metier',
            field=models.TextField(verbose_name='Description du métier'),
        ),
        migrations.AlterField(
            model_name='metier',
            name='label_metier',
            field=models.CharField(max_length=100, verbose_name='Nom du métier'),
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_workshop', models.CharField(max_length=100, verbose_name="Nom de l'atelier")),
                ('quartier', models.CharField(max_length=100, verbose_name="Quartier de l'atelier")),
                ('tel', models.CharField(max_length=80, null=True, verbose_name="Telephone de l'atelier")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Metier', to='api.metier')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coordonnees', to='api.coordonnees')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='api.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='api.service')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='prestation_service',
            field=models.ManyToManyField(related_name='prestation', to='api.service'),
        ),
    ]
