# Generated by Django 5.0.7 on 2024-08-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordonnees_customer_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='label_workshop',
            new_name='label_atelier',
        ),
    ]
